# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				zoglin = true
				arrow = true
				cow = true
				pig = true
				allay = true
				skeleton = true
				bat = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				stray = true
				item = true
				turtle = true
				wither_skeleton = true
				salmon = true
				vindicator = true
				horse = true
				ender_dragon = true
				spectral_arrow = true
				glow_squid = true
				glow_item_frame = false
				snowball = true
				squid = true
				lightning_bolt = true
				creeper = true
				enderman = true
				dragon_fireball = true
				chicken = true
				ravager = true
				donkey = true
				chest_minecart = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				cat = true
				zombie = true
				sheep = true
				fireball = true
				player = true
				villager = true
				wolf = true
				zombie_villager = true
				small_fireball = true
				snow_golem = true
				witch = true
				spider = true
				parrot = true
				ocelot = true
				tropical_fish = true
				goat = true
				silverfish = true
				trident = true
				guardian = true
				llama = true
				llama_spit = true
				husk = true
				item_frame = true

